# Start with the Node.js 14 image
FROM node:14

# Install development tools
RUN npm install typescript -g

# Set a working directory
WORKDIR /app

# Copy the project file
COPY package*.json ./

# Install ALL node_modules, including 'devDependencies'
RUN npm install

# Copy the entire project
COPY . .

# Compile the source code
RUN tsc
