name: Pip.Services Entities microservice in Node.JS

on: 
  push:
    paths:
    - '**'
    - '!README.md'

jobs:
  Default:
    runs-on: ubuntu-18.04
    env:
        GIT_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
        
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
    - uses: actions/checkout@main

  
    ############# Prepare #############

    - name: Install prereq and save build number
      id: build_info
      uses: pip-devops/actions/node/prepare@v1


    # ############# Build and test #############

    - name: Build the component
      uses: pip-devops/actions/node/build@v1

    - name: Test the component
      uses: pip-devops/actions/node/test@v1


    ############# Release to dockerhub #############

    - name: Install powershell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
    
    - name: Install node
      run: |
        cd ~
        curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
        sudo bash nodesource_setup.sh
        sudo apt install nodejs

    - name: Package container
      run: ./package.ps1

    - name: Package lambda
      run: ./pack_lambda.ps1

    - name: Release to Docker Hub
      run: ./publish.ps1
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}


    ############# Clear #############

    - name: Clean up
      uses: pip-devops/actions/node/clear@v1
